version: '3.9'

services:

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo_web
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_NAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_NAME}:${DB_PASSWORD}@mongo:27017/
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  
volumes:
  mongodb:
  mongodb_config:
